server:
  port: 9090
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: system
      password: gautam123
      hikari:
        maximum-pool-size: 100
        minimum-idle: 10
        max-lifetime: 10000
  jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.Oracle10gDialect  
      show-sql: true
      properties:
        formate_sql: true
        hibernate:
          ddl-auto: update
        
        

formapps:
   messages:
     regsuccess: Registration Succesfull:-)
     regfailuer: Registration Failuer
 
   
   
 